# Generated by Django 4.1.10 on 2023-07-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup_detail',
            new_name='user_data',
        ),
    ]
