# Generated by Django 4.1.10 on 2023-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_signup_detail_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
